export const projects = [
    {
        id: 1,
        name: 'My own Protfolio',
        languages: ['react'],
        image : "https://media.giphy.com/media/m2SAii04Q3w9DSx2ZY/giphy.gif",
        category: 'React',
        url: 'https://portfolio-szo89.vercel.app/',
        source: 'https://github.com/Szo89/portfolio',
    },
    {
        id: 2,
        name: "Johanna's project",
        languages: ['html ', 'css ', 'javaScript'],
        image : "https://media.giphy.com/media/a1wmOMSa8rOBT23oR3/giphy.gif",
        category: 'Responsive',
        url: 'https://szo89.github.io/johanna-personal-website/',
        source: 'https://github.com/Szo89/johanna-personal-website',
    },
    {
        id: 3,
        name: 'RoboFriends',
        languages: ['react'],
        image : "https://media.giphy.com/media/wtPVn2rr46ROgXQSmr/giphy.gif",
        category: 'React',
        url: 'https://szo89.github.io/robofriend/',
        source: 'https://github.com/Szo89/robofriend',
    },
    
    {
        id: 4,
        name: 'Election-map',
        languages: ['html ', 'css ', 'javascript'],
        image : "https://media.giphy.com/media/bGUS95z7LlH2UeNyQe/giphy.gif",
        category: 'Javascript',
        url: 'https://szo89.github.io/election-map/',
        source: 'https://github.com/Szo89/election-map',
    },
    {
        id: 5,
        name: 'Guess the word',
        languages: ['html ', 'css ', 'javascript'],
        image : "https://media.giphy.com/media/dlMXHcjREAQwgttKO5/giphy.gif",
        category: 'Javascript',
        url: 'https://szo89.github.io/guess-the-word/',
        source: 'https://github.com/Szo89/guess-the-word',
    },
    {
        id: 6,
        name: 'Github Portfolio',
        languages: ['html ', 'css ', 'javascript'],
        image : "https://media.giphy.com/media/Dxn4kc5S4zwkQg7oS2/giphy.gif",
        category: 'Javascript',
        url: 'https://szo89.github.io/github-repo-gallery/',
        source: 'https://github.com/Szo89/github-repo-gallery',
    },
    
]