export const projects = [
    {
        id: 1,
        name: 'My own Protfolio',
        languages: ['react'],
        image : "https://media1.giphy.com/media/SjcxhwLLy955xvm6Fy/giphy.gif",
        category: 'React',
        url: 'https://github.com/Szo89/portfolio',
        source: 'https://github.com/Szo89/portfolio',
    },
    {
        id: 2,
        name: "Johanna's project",
        languages: ['html ', 'css ', 'javaScript'],
        image : "https://media1.giphy.com/media/SjcxhwLLy955xvm6Fy/giphy.gif",
        category: 'Responsive',
        url: 'https://github.com/Szo89/unplugged-project',
        source: 'https://github.com/Szo89/unplugged-project',
    },
    {
        id: 3,
        name: 'RoboFriends',
        languages: ['react'],
        image : "https://media1.giphy.com/media/SjcxhwLLy955xvm6Fy/giphy.gif",
        category: 'React',
        url: 'https://github.com/Szo89/Animation-Nation',
        source: 'https://github.com/Szo89/Animation-Nation',
    },
    {
        id: 4,
        name: 'Background-gradient',
        languages: ['html ', 'css ', 'javascript'],
        image : "https://media1.giphy.com/media/SjcxhwLLy955xvm6Fy/giphy.gif",
        category: 'Javascript',
        url: 'https://github.com/Szo89/portfolio',
        source: 'https://github.com/Szo89/portfolio',  
    },
    {
        id: 5,
        name: 'Election-map',
        languages: ['html ', 'css ', 'javascript'],
        image : "https://media1.giphy.com/media/SjcxhwLLy955xvm6Fy/giphy.gif",
        category: 'Javascript',
        url: 'https://github.com/Szo89/portfolio',
        source: 'https://github.com/Szo89/portfolio',
    },
    {
        id: 6,
        name: 'To-Do-List',
        languages: ['react'],
        image : "https://media1.giphy.com/media/SjcxhwLLy955xvm6Fy/giphy.gif",
        category: 'React',
        url: 'https://github.com/Szo89/portfolio',
        source: 'https://github.com/Szo89/portfolio',
    }
]